### ISSUE TITLE
TSLintからESLintへの移行

### ISSUE THREAD

**Issue by uta8a** [plageoj/fukagawa-coffee#30]
# 理由

> TSLint [has been deprecated](https://medium.com/palantir/tslint-in-2019-1a144c2317a9) as of 2019.

https://palantir.github.io/tslint/

# 完了要件

- ESLintに移行する
- prettierとESLintがformatOnSaveで効くようにする

# 手順

- ESLintとprettierの拡張はdevcontainerで既に入っている。設定ファイルとnpm packageを入れたらOK

**Comment by plageoj** [comment]
eslint 移行は

- tslint の設定ファイルを消す
- パッケージから tslint を消す
- ng lint （または npx @angular/cli lint）を実行して、出力される指示に従ってパッケージと設定を追加する

でいけるはず。
